name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    # 新增上传 APK 步骤
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        # 指定上传文件的路径，假设 APK 位于项目的 build/outputs/apk/ 里，根据实际路径进行调整
        path: app/build/outputs/apk/debug/app-debug.apk
        name: app-debug.apk
